### ISSUE TITLE
depchase tracebacks when a non-existent binary rpm name is given on the commandline

### ISSUE THREAD

**Issue by KarstenHopp** [fedora-modularity/depchase#9]
$ ./depchase -a x86_64 -c repos.cfg resolve vim
Traceback (most recent call last):
  File "./depchase", line 495, in <module>
    cli(obj={})
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./depchase", line 469, in resolve
    binary, source = solve(solver, pkgnames, selfhost=selfhost)
  File "./depchase", line 360, in solve
    assert not sel.isempty(), "Could not find package for {}".format(n)
AssertionError: Could not find package for vim

I know that vim isn't a binary rpm package, but this should be a little more user friendly.

**Comment by ignatenkobrain** [comment]
> AssertionError: Could not find package for vim

so isn't this enough? ;)
